name: Economia
version: 0.1.2
main: io.github.shidesu.economia.Economia
author: Kao
authors: [Kao, CoolNono]
description: Un plugin permettant la gestion et la création d'une économie sur votre serveur minecraft !
commands:
  ecopaid:
    description: Pour débuguer les Commandes.
    usage: /<command> or /<command> test
    permission:
#depend: [Vault]
softdepend: [Essentials]